### ISSUE TITLE
Production ready and support for Reactive spring stack

### ISSUE THREAD

**Issue by gituserjava** [spring-cloud-incubator/spring-cloud-sleuth-otel#26]
Could you please let me know if this library is fully tested and can be used in Production environment without any technical issues?

Also, does it works well with Reactive spring stack?

Does this support Honeycomb?

**Comment by marcingrzejszczak** [comment]
> Could you please let me know if this library is fully tested and can be used in Production environment without any technical issues?

The tests are passing if you're asking about it. There are companies that use the tool in production. OTel has just been released as GA. OTel instrumentation has not. So it's really difficult to answer your question.

> Also, does it works well with Reactive spring stack?

Yes.

> Does this support Honeycomb?

What do you mean? If Honeycomb has a dedicated exporter then add it to the classpath and register it as a bean.
