### ISSUE TITLE
Baggage missing when using otlp Java agent

### ISSUE THREAD

**Issue by Sutty100** [spring-cloud-incubator/spring-cloud-sleuth-otel#32]
**Describe the bug**
Spring Cloud version: 2020.0.1
Sleuth Otel version: 1.0.0-M5
When running the exact same application with the [Open telemetry Java agent](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases) (v1.0.0 or v0.17.0) baggage stops being passed around my local application. tracer.getBaggage("foo").get() is always an empty string.

If I remove the startup argument to use the agent: 
`-javaagent:/opentelemetry-javaagent-all.jar -Dotel.otlp.endpoint=http://localhost:4317`

Then the baggage starts happily being passed around my application. The baggage is being set via incoming headers.

**Sample**
Sample application that shows this problem attached.
[app-a.zip](https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel/files/6118346/app-a.zip)

**Comment by jkwatson** [comment]
I wouldn't recommend using spring-cloud-sleuth-otel in conjunction with the auto-instrumentation agent at this time. There are incompatibility issues like this one that will make it extremely difficult for them to work together until they are resolved. 

This particular issue is most likely in the agent code, so I would recommend opening and issue in that repository.

**Comment by marcingrzejszczak** [comment]
Hey @Sutty100 can you check the latest snapshots? I've just merged @jkwatson 's PR https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel/pull/34

**Comment by jkwatson** [comment]
@marcingrzejszczak I don't believe that #34 will fix anything involved with agent-sleuth instrumentation/context conflicts. I still strongly advise against using the agent together with sleuth until the agent instrumentation folks can do some additional  compatibility work.

**Comment by jkwatson** [comment]
> Yeah issue still seems to be there. @jkwatson I shall hold off. We were just looking at options to unify tracing across a range of apps which include AWS Serverless and OpenTracing seems to be a promising option that is set to be fully supported by AWS on Lambda and with their library automagically include calls made though the AWS SDK. Looks like as you say we might want to hold off on investigating this further for a while though.

Please create an issue/discussion in the opentelemetry-java-instrumentation repository with your needs, so the folks there know that it's something to prioritize working on.

**Comment by marcingrzejszczak** [comment]
Ok so I will close this one here.
