### ISSUE TITLE
OTLP exporter feature not working

### ISSUE THREAD

**Issue by ponson-thankavel-finastra** [spring-cloud-incubator/spring-cloud-sleuth-otel#41]
**Describe the bug**
Hello Experts, first of all thank you so much for bootstrapping this wonderful project.
I am using Spring Boot 2.4.4 and trying to instrument it using spring cloud sleuth and export using otlp. I am running a Grafana Tempo OTel OTLP receiver at http://localhost:55680.  As, I run my application and access the REST end point, I could see TraceId and SpanId generated in log output. However, the trace info is not exported to the Grafana Tempo collector running at http://localhost:55680. I am using jvmArguments to set "-Dspring.sleuth.otel.exporter.otlp.endpoint". I also tried setting the same variable using application.properties but no luck. There is no error message reported in application log as well.

Anyone please shed some light on how to use the otlp exporter with this 

**Here is the pom.xml file:-**
`<?xml version="1.0" encoding="UTF-8"?>                                                                          `
`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"        `
`  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">           `
`  <modelVersion>4.0.0</modelVersion>                                                                            `
`                                                                                                                `
`  <groupId>org.example</groupId>                                                                                `
`  <artifactId>SpringBootRestMaven</artifactId>                                                                  `
`  <version>1.0-SNAPSHOT</version>                                                                               `
`                                                                                                                `
`  <name>SpringBootRestMaven</name>                                                                              `
`  <!-- FIXME change it to the project's website -->                                                             `
`  <url>http://www.example.com</url>                                                                             `
`                                                                                                                `
`  <parent>                                                                                                      `
`    <groupId>org.springframework.boot</groupId>                                                                 `
`    <artifactId>spring-boot-starter-parent</artifactId>                                                         `
`    <!--<version>2.2.5.RELEASE</version>-->                                                                     `
`    <version>2.4.4</version>                                                                                    `
`    <relativePath />                                                                                            `
`  </parent>                                                                                                     `
`                                                                                                                `
`  <properties>                                                                                                  `
`    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>                                          `
`    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>                                  `
`    <java.version>1.8</java.version>                                                                            `
`    <maven.compiler.source>1.8</maven.compiler.source>                                                          `
`    <maven.compiler.target>1.8</maven.compiler.target>                                                          `
`  </properties>                                                                                                 `
`                                                                                                                `
`  <dependencies>                                                                                                `
`    <dependency>                                                                                                `
`      <groupId>org.springframework.boot</groupId>                                                               `
`      <artifactId>spring-boot-starter-web</artifactId>                                                          `
`    </dependency>                                                                                               `
`    <dependency>                                                                                                `
`      <groupId>org.springframework.boot</groupId>                                                               `
`      <artifactId>spring-boot-starter-actuator</artifactId>                                                     `
`    </dependency>                                                                                               `
`    <dependency>                                                                                                `
`      <groupId>io.micrometer</groupId>                                                                          `
`      <artifactId>micrometer-registry-prometheus</artifactId>                                                   `
`    </dependency>                                                                                               `
`    <dependency>                                                                                                `
`      <groupId>net.logstash.logback</groupId>                                                                   `
`      <artifactId>logstash-logback-encoder</artifactId>                                                         `
`      <version>6.6</version>                                                                                    `
`    </dependency>                                                                                               `
`                                                                                                                `
`    <!-- Sleuth with OpenTelemetry tracer implementation -->                                                    `
`    <dependency>                                                                                                `
`      <groupId>org.springframework.cloud</groupId>                                                              `
`      <artifactId>spring-cloud-starter-sleuth</artifactId>                                                      `
`      <exclusions>                                                                                              `
`        <exclusion>                                                                                             `
`          <groupId>org.springframework.cloud</groupId>                                                          `
`          <artifactId>spring-cloud-sleuth-brave</artifactId>                                                    `
`        </exclusion>                                                                                            `
`      </exclusions>                                                                                             `
`    </dependency>                                                                                               `
`                                                                                                                `
`    <!-- This dependency adds OTel support -->                                                                  `
`    <dependency>                                                                                                `
`      <groupId>org.springframework.cloud</groupId>                                                              `
`      <artifactId>spring-cloud-sleuth-otel-autoconfigure</artifactId>                                           `
`    </dependency>                                                                                               `
`  </dependencies>                                                                                               `
`                                                                                                                `
`  <dependencyManagement>                                                                                        `
`    <dependencies>                                                                                              `
`      <dependency>                                                                                              `
`        <groupId>org.springframework.cloud</groupId>                                                            `
`        <artifactId>spring-cloud-dependencies</artifactId>                                                      `
`        <version>2020.0.2</version>                                                                             `
`        <type>pom</type>                                                                                        `
`        <scope>import</scope>                                                                                   `
`      </dependency>                                                                                             `
`      <dependency>                                                                                              `
`        <groupId>org.springframework.cloud</groupId>                                                            `
`        <artifactId>spring-cloud-sleuth-otel-dependencies</artifactId>                                          `
`        <version>1.0.0-M7</version>                                                                             `
`        <scope>import</scope>                                                                                   `
`        <type>pom</type>                                                                                        `
`      </dependency>                                                                                             `
`    </dependencies>                                                                                             `
`  </dependencyManagement>                                                                                       `
`                                                                                                                `
`  <build>                                                                                                       `
`    <plugins>                                                                                                   `
`      <plugin>                                                                                                  `
`        <groupId>org.springframework.boot</groupId>                                                             `
`        <artifactId>spring-boot-maven-plugin</artifactId>                                                       `
`        <configuration>                                                                                         `
`          <jvmArguments>                                                                                        `
`            -Dspring.sleuth.otel.exporter.otlp.endpoint=http://localhost:55680                                  `
`          </jvmArguments>                                                                                       `
`        </configuration>                                                                                        `
`      </plugin>                                                                                                 `
`    </plugins>                                                                                                  `
`  </build>                                                                                                      `
`                                                                                                                `
`  <repositories>                                                                                                `
`    <repository>                                                                                                `
`      <id>spring-snapshots</id>                                                                                 `
`      <url>https://repo.spring.io/snapshot</url>                                                                `
`      <snapshots><enabled>true</enabled></snapshots>                                                            `
`    </repository>                                                                                               `
`    <repository>                                                                                                `
`      <id>spring-milestones</id>                                                                                `
`      <url>https://repo.spring.io/milestone</url>                                                               `
`    </repository>                                                                                               `
`  </repositories>                                                                                               `
`  <pluginRepositories>                                                                                          `
`    <pluginRepository>                                                                                          `
`      <id>spring-snapshots</id>                                                                                 `
`      <url>https://repo.spring.io/snapshot</url>                                                                `
`    </pluginRepository>                                                                                         `
`    <pluginRepository>                                                                                          `
`      <id>spring-milestones</id>                                                                                `
`      <url>https://repo.spring.io/milestone</url>                                                               `
`    </pluginRepository>                                                                                         `
`  </pluginRepositories>                                                                                         `
`</project>                                                                                                      `

**Sample**
**com.finastra.springboot.rest.SpringBootDemoApplication**

package com.finastra.springboot.rest;

import javax.annotation.PostConstruct;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;

@SpringBootApplication 
public class SpringBootDemoApplication {

    public static void main(String[] args) {
        ConfigurableApplicationContext context = SpringApplication.run(SpringBootDemoApplication.class, args);
    }

    @PostConstruct
    public void init() {

    }
}

**com.finastra.springboot.rest.controller.EmployeeController**

package com.finastra.springboot.rest.controller;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping(path = "/")
public class EmployeeController 
{
    @GetMapping(path="/employees", produces = "application/json")
    public String getEmployees() throws Exception
    {
    	System.out.println("Inside EmployeeController.getEmployees");

        return "{ test: \"hello world\" }";
    }
}

**application.properties**
logging.group.tomcat=org.apache.catalina, org.apache.coyote, org.apache.tomcat

logging.level.root=debug
logging.level.tomcat=debug

management.endpoints.web.exposure.include=prometheus,metrics,health
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.prometheus=metrics
management.endpoints.web.path-mapping.metrics=actuator/metrics
management.endpoints.web.path-mapping.health=actuator/health

spring.sleuth.otel.exporter.otlp.endpoint=http://localhost:55680

**Comment by ponson-thankavel-finastra** [comment]
Please note that the instrumentation and trace export works perfectly fine with opentelemetry-java-instrumentation mentioned here - https://github.com/open-telemetry/opentelemetry-java-instrumentation .

**Comment by jkwatson** [comment]
I think you're missing the otlp exporter dependency and a netty transport:

```
io.opentelemetry:opentelemetry-exporter-otlp:1.0.1
io.grpc:grpc-netty-shaded:1.35.0
```
are both needed to enable the otlp exporter.

(apologies for the gradle style maven coordinates)

**Comment by ponson-thankavel-finastra** [comment]
@jkwatson ... you are spot on.... Thanks a lot... I added latest versions of those dependencies and started seeing trace in Tempo... full project is available here - https://github.com/PonsonT/spring-boot-sleuth-otel-otlp

Thanks again @jkwatson ...
