### ISSUE TITLE
Cloud Sleuth Autoconfigure ships spring factories definitions for classes it doesn't manage

### ISSUE THREAD

**Issue by bclozel** [spring-cloud-incubator/spring-cloud-sleuth-otel#42]
See spring-projects-experimental/spring-native#673 for background.

We've noticed that the `spring-cloud-sleuth-otel-autoconfigure` artifact ships with [a `spring.factories` file containing definitions for classes it doesn't manage](https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel/blob/62adab8e88116d0e77a38fe11abe1a177671f854/spring-cloud-sleuth-otel-autoconfigure/src/main/resources/META-INF/spring.factories#L8-L11) (i.e. are not shipped with the JAR). While the AOT issue will be handled in spring-native, we just thought that this could be an oversight you'd like to fix.

Thanks!

**Comment by marcingrzejszczak** [comment]
Oh yeah! Thanks for pointing it out!

**Comment by bclozel** [comment]
That was super quick, thanks!
