### ISSUE TITLE
Exporters should be plural in docs

### ISSUE THREAD

**Issue by jimshowalter** [spring-cloud-incubator/spring-cloud-sleuth-otel#46]
This change added exporters: https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel/commit/0042954d552b9428b90f11df91305392e52283c6
But it has it singular: "exporter".
Mavencentral has it plural: https://search.maven.org/artifact/io.opentelemetry/opentelemetry-exporters-zipkin/0.9.1/jar

**Comment by jkwatson** [comment]
That is not the correct library. See here: https://search.maven.org/artifact/io.opentelemetry/opentelemetry-exporter-zipkin/1.1.0/jar
