### ISSUE TITLE
ETA for a GA Version

### ISSUE THREAD

**Issue by PatrikSteuer** [spring-cloud-incubator/spring-cloud-sleuth-otel#56]
**Describe the Question**
Do major issues exist which have to be resolved for a GA release? We would like to consume the libraries without using the milestone repositories.

**Comment by marcingrzejszczak** [comment]
Yes, the major issue is otel-java-instrumentation being in alpha version. Once they go GA and are not alpha anymore then we will consider making this GA (or even merge it to core of Sleuth).

**Comment by jonatan-ivanov** [comment]
@PatrikSteuer You can check the progress at these places:
- OTel issue to release a stable/GA version: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/2892
- It has a dependency: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/2713
(The list has 90 items and 4 of them are completed right now)
- You can also check Maven Central to see that [`opentelemetry-instrumentation-api`](https://search.maven.org/search?q=g:io.opentelemetry.instrumentation%20AND%20a:opentelemetry-instrumentation-api) is in alpha

**Comment by PatrikSteuer** [comment]
Thanks a lot!

**Comment by huggsboson** [comment]
Just to be clear you only rely on a very small number of classes in otel-instrumentation libs (which will hopefully be refactored into otel-instrumentation-api and go GA sooner than otel-instrumentation).  

For the most part otel-api and otel-sdk libraries in Java *are* GA'd it's just that you've taken out a dependency on some classes in the instrumentation libs and the automatic instrumentation libs aren't GA'd.

**Comment by marcingrzejszczak** [comment]
> Just to be clear you only rely on a very small number of classes in otel-instrumentation libs (which will hopefully be refactored into otel-instrumentation-api and go GA sooner than otel-instrumentation).

Hopefully!

> For the most part otel-api and otel-sdk libraries in Java are GA'd it's just that you've taken out a dependency on some classes in the instrumentation libs and the automatic instrumentation libs aren't GA'd.

Yes, but still it means that otel-instrumentation is not ga, so this project can't be ga.

**Comment by almogtavor** [comment]
@jonatan-ivanov @marcingrzejszczak Why is this project still in the experimental phase after otel 1.18.0 has been released?

**Comment by jonatan-ivanov** [comment]
@almogtavor OTel 1.18.0 was released less than two days ago (around 2022-09-14 22:39).
Spring Cloud Sleuth OTel 1.1.0 was released a few hours before you wrote this comment.

Also, OTel Tracing being stable could be still an overstatement since both [`opentelemetry-semconv`](https://search.maven.org/artifact/io.opentelemetry/opentelemetry-semconv/1.18.0-alpha/jar) and [`opentelemetry-instrumentation-api-semconv`](https://search.maven.org/artifact/io.opentelemetry.instrumentation/opentelemetry-instrumentation-api-semconv/1.18.0-alpha/jar) are alpha (see their version number: `1.18.0-alpha`).

**Comment by huggsboson** [comment]
hi @jonatan-ivanov.  Thanks for all of your hard work on this lib.  What's the criteria for moving this from experimental to stable?  This lib's use of the semconv libs is on attributes that look extremely stable to me and wouldn't indicate a risk in using this library.

Context: Getting this lib out of experimental mode helps us undo some workarounds we are doing in our builds to use this lib which are causing some challenges when upgrading spring-boot.  Thanks so much for any help you can provide.

**Comment by jonatan-ivanov** [comment]
Spring Cloud Sleuth OTel [1.1.0 was released (GA)](https://github.com/spring-projects-experimental/spring-cloud-sleuth-otel/releases/tag/v1.1.0) a few days ago. If you needed GA artifacts in Maven Central you can find those now [here](https://search.maven.org/artifact/org.springframework.cloud/spring-cloud-sleuth-otel).

I have a feeling that we are not talking about the same thing: if semconv is extremely stable as you said, I'm not sure I get why both [`opentelemetry-semconv`](https://search.maven.org/artifact/io.opentelemetry/opentelemetry-semconv/1.18.0-alpha/jar) and [`opentelemetry-instrumentation-api-semconv`](https://search.maven.org/artifact/io.opentelemetry.instrumentation/opentelemetry-instrumentation-api-semconv/1.18.0-alpha/jar) are still in alpha (see their version number: `1.18.0-alpha`). Also, I don't get why it had [lots of breaking changes](https://github.com/spring-projects-experimental/spring-cloud-sleuth-otel/commit/69b4384a13349f0d1f24fc47b23af23e30eb3ec4) at the last release. Is this the same thing you are talking about? If so, what am I missing?

**Comment by huggsboson** [comment]
I was looking here:
https://github.com/open-telemetry/opentelemetry-java/tree/main/semconv  (not updated in 2 months, your uses semconv look like very stable attributes, I'm not sure if they've been refactoring class names)

I was mostly talking about the attribute names and it doesn't seem like you have many dependencies on the semconv attribute names.

**Comment by jonatan-ivanov** [comment]
Check [instrumentation-api-semconv](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation-api-semconv) which got more frequent (and breaking) changes. On the other hand, not updated does not mean stable to me. Please also check the [semconv specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/README.md), it is marked as experimental so the attribute definitions are not stable either (hence the `-alpha` in `opentelemetry-semconv`).

**Comment by huggsboson** [comment]
Just to follow up I didn't realize the 1.1.0 was a GA release as opposed to a milestone/experimental release.  I believe that has fixed our issues.
