### ISSUE TITLE
Following quick-start instructions results in exception

### ISSUE THREAD

**Issue by jimshowalter** [spring-cloud-incubator/spring-cloud-sleuth-otel#58]
We're trying to migrate from Sleuth/Brave to Sleuth/opentelemetry.

Followed the instructions in https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel#quick-start.

Tried to run integration tests, but got:

java.lang.ClassNotFoundException: io.opentelemetry.spi.trace.TracerProviderFactory

Gradle configuration:

sleuthVersion=3.0.3
sleuthOpentelemetryVersion=1.0.0-M2
zipkinExporterVersion=1.3.0

api("org.springframework.cloud:spring-cloud-starter-sleuth:${sleuthVersion}") {
  exclude group: 'org.springframework.cloud', module: 'spring-cloud-sleuth-brave'
}
api "org.springframework.cloud:spring-cloud-sleuth-otel-autoconfigure:${sleuthOpentelemetryVersion}"
api "org.springframework.cloud:spring-cloud-sleuth-zipkin:${sleuthVersion}"
api "io.opentelemetry:opentelemetry-exporter-zipkin:${zipkinExporterVersion}"

**Comment by marcingrzejszczak** [comment]
You haven't followed the quick start instructions at all really.

```xml
 <!-- Spring Cloud Sleuth requires a Spring Cloud BOM -->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <!-- Provide the latest stable Spring Cloud release train version (e.g. 2020.0.0) -->
                <version>${release.train.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-sleuth-otel-dependencies</artifactId>
                <!-- Provide the version of the Spring Cloud Sleuth OpenTelemetry project -->
                <version>${spring-cloud-sleuth-otel.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <!-- Boot's Web support -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!-- Sleuth with OpenTelemetry tracer implementation -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-sleuth</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.cloud</groupId>
                    <artifactId>spring-cloud-sleuth-brave</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!-- This dependency adds OTel support -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-sleuth-otel-autoconfigure</artifactId>
        </dependency>
    </dependencies>

<!-- You 'll need those to add OTel support -->
        <repositories>
            <repository>
                <id>spring-snapshots</id>
                <url>https://repo.spring.io/snapshot</url>
                <snapshots><enabled>true</enabled></snapshots>
            </repository>
            <repository>
                <id>spring-milestones</id>
                <url>https://repo.spring.io/milestone</url>
            </repository>
        </repositories>
        <pluginRepositories>
            <pluginRepository>
                <id>spring-snapshots</id>
                <url>https://repo.spring.io/snapshot</url>
            </pluginRepository>
            <pluginRepository>
                <id>spring-milestones</id>
                <url>https://repo.spring.io/milestone</url>
            </pluginRepository>
        </pluginRepositories>
```

In the instructions we tell you to use the `spring-cloud-dependencies` release train BOM - which you don't use. Also we tell you to use the latest Sleuth OTel version - which you don't either (https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel/releases/tag/v1.0.0-M7). Finally, you don't need to provide the zipkinExporter version yourself cause we're using the OpenTelemetry BOM - https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel/blob/main/spring-cloud-sleuth-otel-dependencies/pom.xml#L48-L54

**Comment by jimshowalter** [comment]
Gradle says: "Could not find org.springframework.cloud:spring-cloud-sleuth-otel-autoconfigure:1.0.0-M7."

We've added the milestone repos. We aren't allowed to use snapshot repos.

**Comment by jimshowalter** [comment]
It was the snapshot repos. We're not supposed to use snapshots, but we'll get an exemption for now.
