### ISSUE TITLE
Add support for toggling OpenTelemetry bean builder to register with global

### ISSUE THREAD

**Issue by jimshowalter** [spring-cloud-incubator/spring-cloud-sleuth-otel#62]
We wound up having to do this:

```java
// Two overrides of default configuration in Sleuth/OTEL.
public class OtelAutoConfigurationOverrides {

  @Bean
  @ConditionalOnMissingBean
  // This override is required because the default just returns .build(), but we need
  // .buildAndRegisterGlobal().
  OpenTelemetry otel(SdkTracerProvider tracerProvider, ContextPropagators contextPropagators) {
    return OpenTelemetrySdk.builder()
        .setTracerProvider(tracerProvider)
        .setPropagators(contextPropagators)
        .buildAndRegisterGlobal(); <<< WE NEED THIS BEHAVIOR
  }
...

```java
@Configuration
@Import(OtelAutoConfigurationOverrides.class)
@PropertySource("classpath:our-property-source.properties")
public class OurConfig {}
```

You could add an @ Value to the signature that defaults to not registering globally, and in the implementation return the .build() when false and .buildAndRegisterGlobal() when true.

If there's some other way to achieve this without copying OtelAutoConfiguration's implementation, please explain how to do it.

**Comment by marcingrzejszczak** [comment]
So @jkwatson do you think we should add it or not?

**Comment by jkwatson** [comment]
Having registering the global as an *option* seems like a fine idea to me.

**Comment by marcingrzejszczak** [comment]
I think that a good option is to just register your own `OpenTelemetry` bean as you do it at this point. You don't have to override the default configuration. just register the `OpenTelemetry` bean and that should be fine.
