### ISSUE TITLE
Add support to toggle Sampler bean configuration

### ISSUE THREAD

**Issue by jimshowalter** [spring-cloud-incubator/spring-cloud-sleuth-otel#64]
We had to do this:

```java
  @Bean
  @ConditionalOnMissingBean
  // This override is required because the default sampler that comes with OtelAutoConfiguration is
  // TraceIdRatioBased. In our case the API gateway is going to make the decision whether to sample
  // a request or not, and all downstream services will simply propagate the sampling flag in the context
  // that they receive.
  Sampler otelSampler() {
    return Sampler.parentBased(Sampler.alwaysOff());
  }
```

It would be convenient to be able to toggle the Sampler bean by configuration, perhaps with a list of options like "default" and "always-honor-parent", etc.

**Comment by jimshowalter** [comment]
We don't mind overriding beans--that's normal in Spring. But some of the beans in auto-configure are pretty involved, and overriding those creates a double-maintenance problem. (Sampler isn't complicated.)

**Comment by marcingrzejszczak** [comment]
We're not planning on making everything configurable via properties. You can create your own starter that your apps can use with your custom setup.
