### ISSUE TITLE
Getting Configuration with name 'releaseTrainVersion' not found 

### ISSUE THREAD

**Issue by meSunnySrivastava** [spring-cloud-incubator/spring-cloud-sleuth-otel#68]
Getting Configuration with name 'releaseTrainVersion' not found with 
```dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${releaseTrainVersion}"
        mavenBom "org.springframework.cloud:spring-cloud-sleuth-otel-dependencies:${springCloudSleuthOtelVersion}"
    }
}
```

I am referring the configs mentioned here 
https://spring-cloud-incubator.github.io/spring-cloud-sleuth-otel/docs/current/reference/html/howto.html#howto

**Comment by meSunnySrivastava** [comment]
I have added following plugin config also in my gradle file 
id "io.spring.dependency-management" version "1.0.11.RELEASE"

**Comment by marcingrzejszczak** [comment]
I've seen you ask this question on Gitter. Please do not cross post.

`releaseTrainVersion` means a Spring Cloud release train version - please check this website for more information https://spring.io/projects/spring-cloud

**Comment by meSunnySrivastava** [comment]
Yes I found the Gitter after I raised the question here. 
Sorry for not closing.
