### ISSUE TITLE
SpanReporters not registered

### ISSUE THREAD

**Issue by gquintana** [spring-cloud-incubator/spring-cloud-sleuth-otel#80]
**Describe the bug**
SpanReporters are not registered in SdkTracerProvider

1. [OtelExporterConfiguration.java#L59](https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel/blob/main/spring-cloud-sleuth-otel-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/otel/OtelExporterConfiguration.java#L59) : `reporters.getIfAvailable(ArrayList::new)` returns an empty list during init
2. [OtelAutoConfiguration.java#L97](https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel/blob/v1.1.0-M1/spring-cloud-sleuth-otel-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/otel/OtelAutoConfiguration.java#L97) : `reporters.getIfAvailable(ArrayList::new)` now returns a list containing to elements 
3. [OtelAutoConfiguration.java#L98](https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel/blob/v1.1.0-M1/spring-cloud-sleuth-otel-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/otel/OtelAutoConfiguration.java#L98) +  [OtelExporterConfiguration.java#L62](https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel/blob/main/spring-cloud-sleuth-otel-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/otel/OtelExporterConfiguration.java#L62) each SpanExporter gets replaced by an empty `CompositeSpanExporter` 

The behaviour seems to change depending on the order of Spring beans initialization

**Sample**

```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-sleuth</artifactId>
<version>3.1.0-M1</version>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.cloud</groupId>
					<artifactId>spring-cloud-sleuth-brave</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-sleuth-otel-autoconfigure</artifactId>
				<version>1.1.0-M1</version>
		</dependency>
		<dependency>
			<groupId>io.opentelemetry</groupId>
			<artifactId>opentelemetry-exporter-otlp</artifactId>
				<version>1.5.0</version>
		</dependency>
		<dependency>
			<groupId>io.opentelemetry</groupId>
			<artifactId>opentelemetry-exporter-logging</artifactId>
				<version>1.5.0</version>
		</dependency>
```

**Comment by marcingrzejszczak** [comment]
Hi! Do you have a small sample that reproduces this problem? It will be easier for us to fix this if you have one
